
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { ExtendedDatabase } from '@/types/supabase-custom';

const SUPABASE_URL = "https://nxahrnpuooxbafyqixpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54YWhybnB1b294YmFmeXFpeHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjUzNTUsImV4cCI6MjA2MzY0MTM1NX0.gP5HSbovIDgSE5HRsWBj7hEAqJtEDxEPrSuzAY7Pzwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
