
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgxefmlqhnldncuampun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneGVmbWxxaG5sZG5jdWFtcHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzIwMzcsImV4cCI6MjA1OTk0ODAzN30.8DATfDnbnVB__lQtenpAjJuZvQMjn_X4mnwNmFMFUmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
